# Generated by Django 3.2.4 on 2021-06-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_student_wallet'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
