# Generated by Django 3.0.2 on 2021-06-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210629_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='units_left',
        ),
    ]
