# Generated by Django 3.2.4 on 2021-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_studentaccount_units_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdeposit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentlessonbill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
