# Generated by Django 3.2.4 on 2021-06-10 18:02

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210607_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.user_image_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='interests',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prioroty',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
