# Generated by Django 3.2.4 on 2021-06-10 18:14

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210610_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='man.png', null=True, upload_to=employee.models.user_image_path),
        ),
    ]
