# Generated by Django 3.2.4 on 2021-06-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='prioroty',
            new_name='priority',
        ),
    ]
