# Generated by Django 3.2.4 on 2021-06-03 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('student', '0003_auto_20210603_1638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('homework', 'homework'), ('classwork', 'classwork'), ('curriculum', 'curriculum'), ('', ''), ('', ''), ('', ''), ('', '')], default='1', max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(choices=[('Calculus', 'Calculus'), ('Computer Science', 'Computer Science'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('History', 'History'), ('Academic Advising', 'Academic Advising'), ('Advanced Math', 'Advanced Math')], default='1', max_length=30)),
                ('classwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_classwork', to='activity.submission')),
                ('homework_sent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_homework_sent', to='activity.submission')),
                ('homework_submissions', models.ManyToManyField(to='activity.Submission')),
                ('students', models.ManyToManyField(to='student.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
