# Generated by Django 3.2.4 on 2021-06-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('homework', 'homework'), ('classwork', 'classwork'), ('curriculum', 'curriculum'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lesson', 'Lesson'), ('Advising', 'Advising'), ('Administrative', 'Administrative'), ('Other', 'Other')], max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
