# Generated by Django 3.2.4 on 2021-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210603_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
