# Generated by Django 3.2.4 on 2021-06-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210608_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework_sent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_homework_sent', to='activity.submission'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_submissions',
            field=models.ManyToManyField(blank=True, null=True, to='activity.Submission'),
        ),
    ]
