# Generated by Django 3.2.4 on 2021-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_submission_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='homework_sent',
            new_name='homework',
        ),
    ]
