# Generated by Django 3.2.4 on 2021-06-09 17:11

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_rename_homework_sent_lesson_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='account_type',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=activity.models.user_submission),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('Homework', 'Homework'), ('classwork', 'classwork'), ('curriculum', 'curriculum'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=20),
        ),
    ]
