# Generated by Django 3.2.4 on 2021-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_submission_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Computer Science', 'Computer Science'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('History', 'History'), ('Academic Advising', 'Academic Advising'), ('Compeetitive Math', 'Compeetitive Math'), ('Projects', 'Projects'), ('Essay Writing', 'Essay Writing')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('Homework_Submission', 'Homework_Submission'), ('Classwork', 'Classwork'), ('Curriculum', 'Curriculum'), ('Homework', 'Homework')], max_length=20),
        ),
    ]
