# Generated by Django 3.2.4 on 2021-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20210716_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Computer Science', 'Computer Science'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('History', 'History'), ('Academic Advising', 'Academic Advising'), ('Competitive Math', 'Competitive Math'), ('Projects', 'Projects'), ('Essay Writing', 'Essay Writing')], default='Academic Advising', max_length=30),
        ),
    ]
