# Generated by Django 3.2.4 on 2021-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_alter_lesson_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Computer Science', 'Computer Science'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('History', 'History'), ('Academic Advising', 'Academic Advising'), ('Competitive Math', 'Competitive Math'), ('Projects', 'Projects'), ('Essay Writing', 'Essay Writing'), ('ACT Science', 'ACT Science'), ('ACT Math', 'ACT Math'), ('ACT English', 'ACT English'), ('SAT Math', 'SAT Math'), ('SAT English', 'SAT English'), ('SSAT', 'SSAT'), ('PSAT', 'PSAT'), ('LSAT', 'LSAT'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS')], default='Academic Advising', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
    ]
