# Generated by Django 3.2.4 on 2021-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210603_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
