# Generated by Django 3.2.4 on 2021-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
    ]
