# Generated by Django 3.2.4 on 2021-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
    ]
