# Generated by Django 3.2.4 on 2021-06-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210610_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exams',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
    ]
