# Generated by Django 3.2.4 on 2021-07-27 15:51

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_student_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='man.png', null=True, upload_to=student.models.user_image_path),
        ),
    ]
