# Generated by Django 3.2.4 on 2021-08-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_employers_manager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
